/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DanbooruTagHelper: typeof import('./components/DanbooruTagHelper.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    PromptTextarea: typeof import('./components/PromptTextarea.vue')['default']
    SettingPage: typeof import('./components/SettingPage.vue')['default']
    WildcardManager: typeof import('./components/WildcardManager.vue')['default']
  }
}
